name: Testing and linting on each push

on:
  push:
    branches: [ "*" ]
  pull_request:
    branches: [ "*" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        make setup-dev
    - name: Lint
      run: |
        export PIPENV_IGNORE_VIRTUALENVS=1
        make lint
    - name: Test with pytest
      run: |
        export PIPENV_IGNORE_VIRTUALENVS=1
        make test
